In [1]:
import pandas as pd

In [4]:
cookie_cats_cleaned = pd.read_csv("../data/cookie_cats.csv")
cookie_cats_cleaned.head(10)

   userid  version  sum_gamerounds  retention_1  retention_7
0     116  gate_30               3        False        False
1     337  gate_30              38         True        False
2     377  gate_40             165         True        False
3     483  gate_40               1        False        False
4     488  gate_40             179         True         True
5     540  gate_40             187         True         True
6    1066  gate_30               0        False        False
7    1444  gate_40               2        False        False
8    1574  gate_40             108         True         True
9    1587  gate_40             153         True        False

In [5]:
cookie_cats_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90189 entries, 0 to 90188
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   userid          90189 non-null  int64
 1   version         90189 non-null  object
 2   sum_gamerounds  90189 non-null  int64
 3   retention_1     90189 non-null  bool
 4   retention_7     90189 non-null  bool
dtypes: bool(2), int64(2), object(1)
memory usage: 2.2+ MB

In [6]:
cookie_cats_cleaned.describe()

             userid  sum_gamerounds
count  9.018900e+04    90189.000000
mean   4.998412e+06       51.872457
std    2.883286e+06      195.050858
min    1.160000e+02        0.000000
25%    2.512230e+06        5.000000
50%    4.995815e+06       16.000000
75%    7.496452e+06       51.000000
max    9.999861e+06    49854.000000

In [7]:
cookie_cats_cleaned = cookie_cats_cleaned.dropna()

In [8]:
cookie_cats_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90189 entries, 0 to 90188
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   userid          90189 non-null  int64
 1   version         90189 non-null  object
 2   sum_gamerounds  90189 non-null  int64
 3   retention_1     90189 non-null  bool
 4   retention_7     90189 non-null  bool
dtypes: bool(2), int64(2), object(1)
memory usage: 2.2+ MB

In [9]:
cookie_cats_cleaned['sum_gamerounds'].sort_values(ascending=False).head(10)

57702    49854
7912      2961
29417     2640
43671     2438
48188     2294
46344     2251
87007     2156
36933     2124
88328     2063
6536      2015
Name: sum_gamerounds, dtype: int64

In [11]:
Q1 = cookie_cats_cleaned['sum_gamerounds'].quantile(0.25)
Q3 = cookie_cats_cleaned['sum_gamerounds'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = cookie_cats_cleaned[(cookie_cats_cleaned['sum_gamerounds'] < lower_bound) | (cookie_cats_cleaned['sum_gamerounds'] > upper_bound)]

In [ ]:
cookie_cats_cleaned = cookie_cats_cleaned[cookie_cats_cleaned['sum_gamerounds'] <= 45000].copy()

In [13]:
cookie_cats_cleaned.to_csv("../data/cookie_cats_cleaned.csv", index=False)